//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/BeaconMessage.msg.
//

#ifndef __VEINS_BEACONMESSAGE_M_H
#define __VEINS_BEACONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class BeaconMessage;

}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/modules/messages/DemoSafetyMessage_m.h" // import veins.modules.messages.DemoSafetyMessage

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>messages/BeaconMessage.msg:30</tt> by opp_msgtool.
 * <pre>
 * packet BeaconMessage extends DemoSafetyMessage
 * {
 *     Coord senderPos;
 *     Coord senderSpeed;
 *     int senderId;
 * }
 * </pre>
 */
class BeaconMessage : public ::veins::DemoSafetyMessage
{
  protected:
    Coord senderPos;
    Coord senderSpeed;
    int senderId = 0;

  private:
    void copy(const BeaconMessage& other);

  protected:
    bool operator==(const BeaconMessage&) = delete;

  public:
    BeaconMessage(const char *name=nullptr, short kind=0);
    BeaconMessage(const BeaconMessage& other);
    virtual ~BeaconMessage();
    BeaconMessage& operator=(const BeaconMessage& other);
    virtual BeaconMessage *dup() const override {return new BeaconMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Coord& getSenderPos() const;
    virtual Coord& getSenderPosForUpdate() { return const_cast<Coord&>(const_cast<BeaconMessage*>(this)->getSenderPos());}
    virtual void setSenderPos(const Coord& senderPos);

    virtual const Coord& getSenderSpeed() const;
    virtual Coord& getSenderSpeedForUpdate() { return const_cast<Coord&>(const_cast<BeaconMessage*>(this)->getSenderSpeed());}
    virtual void setSenderSpeed(const Coord& senderSpeed);

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BeaconMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BeaconMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::BeaconMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::BeaconMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_BEACONMESSAGE_M_H

